apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
data:
  SERVICE_PORT: "8080"

---

apiVersion: v1
kind: Secret
metadata:
  name: service-secret
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: root